services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    
    volumes:
      - ollama:/root/.ollama

    command: >
      sh -c "ollama mistral --keepalive=-1m"

    restart: always 

  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"


